### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by RunAtTekky** [ajeetdsouza/clidle#9] opened 2024-05-13 13:50 UTC
![connection_refused](https://github.com/ajeetdsouza/clidle/assets/110292431/f6b51335-8cdb-4483-a5ba-a5a422f22ac5)
### I'm getting this when trying to run the following command
`ssh clidle.duckdns.org -p 3000`

**Comment by ajeetdsouza** [comment] 2024-07-24 22:13
Duplicate of #8.

**Closed as completed** 2024-07-24 22:13 UTC
